# 端口配置
server:
  port: 8081
# MySQL配置
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hfuugraduate?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
# 解决什么问题来着？解决引入swagger接口文档的情况
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# MongoDB配置
  data:
    mongodb:
      uri: mongodb://hfuu:123456@localhost:27017/hfuugraduate
# MyBatis配置
mybatis:
  type-aliases-package: com.hfuu.graduate.entity
# MongoDB配置
